# Generated by Django 2.2.7 on 2019-11-25 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_auto_20191125_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.CharField(max_length=40)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drf.Customer')),
            ],
        ),
    ]
